### ISSUE TITLE
Global Chat not working?

### ISSUE THREAD

**Issue by Galadriel1640** [lucko/gChat#1]
I have a Spigot server connecting to a Sponge server, and cannot get two things to work:
1: the spigot server wont show tags, while the sponge one does.
2: i cannot seem to access any form of global chat, only single server side.

I am using LuckPerms and gChat together, with the only other plugins being used are:
  Nucleus on the Sponge server
  and Essentials on the Spigot server (i took out essentialsxchat to see if that would fix the issue, which it did not)

**Comment by lucko** [comment]
Are you sure you're connecting through the proxy? Everything should be handled at that level.

**Comment by Galadriel1640** [comment]
To my knowledge yes. Prefixes didn't work until I installed it and I for sure have it in the proxy plugins folder

**Comment by Galadriel1640** [comment]
As for the physical connection, I am definitely logging in through the proxy

**Comment by lucko** [comment]
Does it enable ok?

**Comment by Galadriel1640** [comment]
Yep! "Loaded plugin gChat version 1.0.0 by Luck"
[gChat] enabling gChat v1.0.0
Enabled plugin gChat version 1.0.0 by Luck

**Comment by lucko** [comment]
Alright then, in that case:

Any chat messages sent through the proxy should be picked up by gChat, and won't be sent onto the backend spigot servers.

Make sure everything is correct in your config too.

**Comment by Galadriel1640** [comment]
It's currently the default config that is set to not require permissions, and I don't see any other options that would effect server to server?

**Comment by lucko** [comment]
Shouldn't do, no.

**Comment by Galadriel1640** [comment]
So am I just doing something wrong or are you stumped too?

**Comment by Galadriel1640** [comment]
I just noticed, I am getting an error on the spigot server, but it is related to essentials chat, not gchat

**Comment by lucko** [comment]
Yeah, I don't really know why that is.

**Comment by Galadriel1640** [comment]
Alright, thanks anyways!

**Comment by lucko** [comment]
Can you pastebin the error?

**Comment by Galadriel1640** [comment]
Just went through my logs and for some reason they didn't save yesterday's.... The error was from essentials chat saying that it was not connecting or saving chat
