### ISSUE TITLE
java.lang.NoClassDefFoundError: net/md_5/bungee/log/ConciseFormatter

### ISSUE THREAD

**Issue by craving-death** [lucko/gChat#11]
Error enabling plugin.
Waterfall-296
gChat build 6
https://gist.github.com/craving-death/5f09cf71fd8a1c50fca5d163c12b2e37

**Comment by TechnicProblem** [comment]
Having the same problem. Waterfall-296

**Comment by lucko** [comment]
Fixed in 4e2e0b4d9b806ff3761f0677ca9f626263a3b136
