### ISSUE TITLE
GChat or LuckPermissions no compatible con MaddyCaptcha

### ISSUE THREAD

**Issue by SolarisPKN** [lucko/gChat#2]
Con el plugin permissionesx y essentialsxchat funcionaba, supongo, que es porque con esos plugins permitia que el mensaje se vea en la consola entonces maddycaptcha lo detectaba en cambio como gchat no muestra el mensaje del jugador en la consola maddycaptcha no lo detecta

**Comment by SolarisPKN** [comment]
ahora me di cuenta que los plugins que requieren que el usuario escriba en el chat algo no funcionan con gchat , ej: scrable, ultra permissions, bangui, etc

**Comment by lucko** [comment]
Sorry, I can only provide support in English.

**Comment by SolarisPKN** [comment]
Pardon, With the permissionesx plugin and essentialsxchat worked, I suppose, it is because with those plugins allowed the message to be seen in the console then maddycaptcha detected it instead as gchat does not display the message of the player in the console maddycaptcha does not detect it.


Now I realized that the plugins that require the user to write in the chat something do not work with gchat, eg: scrable, ultra permissions, bangui, etc.

**Comment by lucko** [comment]
Correct, that's the nature of global chat.

The message never gets passed through to the backend.

**Comment by SolarisPKN** [comment]
Would you solve it ... or would you recommend some help? How to make the captcha detect it?

**Comment by SolarisPKN** [comment]
and chat per server? (gchat.send.(world or server), gchat.receive.(world or server)
