### ISSUE TITLE
Not showing any prefixes or suffixes

### ISSUE THREAD

**Issue by PoempelPinguin** [lucko/gChat#5]
Hi, I set up a spigot server and a bungeecord proxy. Running LuckPerms and gChat, but chat does not show any prefixes and/or suffixes. I left gChat config default, `lp user poempelpinguin info` shows up correct group and prefix... :(

**Comment by lucko** [comment]
does `lpb user poempelpinguin info` show the correct data?

**Comment by PoempelPinguin** [comment]
it shows "unknown command" although LuckPerms is setup on the BungeeCord =/ I checked the network setup, it is configured as told in the wiki and notifications are shown.

**Comment by lucko** [comment]
Check your startup log on the proxy.

Make sure you're running the lpb command in the proxy console.

**Comment by PoempelPinguin** [comment]
It seems it does not load LuckPerms correctly. Maybe you have an idea why this is?
https://pastebin.com/J09A7yk2

**Comment by lucko** [comment]
Use the BungeeCord version
https://luckperms.github.io/

**Comment by PoempelPinguin** [comment]
Wtf I thought I had... It works.
I'm very sorry I took your time...

**Comment by lucko** [comment]
No worries
