### ISSUE TITLE
[Feature Request] clickable links

### ISSUE THREAD

**Issue by Magi1053** [lucko/gChat#9]
I'm using the [Velocity port](https://github.com/N3FS/gChat) of this mod, but I think this might be a core feature request. When I paste a link in the chat, I am unable to click it (using client 1.12.2). I thought it would be nice if it detected hyperlinks in the chat and automatically made them clickable.

**Comment by lucko** [comment]
Yep we can do this 😉 

@md678685

`LegacyComponentSerializer.legacyLinking()` serializer will do this.
